apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: site-static-monitor
spec:
  selector:
    matchLabels:
      app: nginx-static
  endpoints:
  - port: "80"  # Changed to a string
    path: /metrics